=== ehenderson828/xml-jquery-final/data/schema/eric.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
   CMT-117 & CMT-225

   XML & jQuery Final Project
   Author: Eric Henderson
   Date: 12/8/25

   Filename:          eric.xsd
   Supporting Files:  eric.xml
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="ericsProjects">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ericsProject" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Title" type="xs:string"/>
              <xs:element name="Description" type="xs:string"/>
              <xs:element name="TimeToComplete" type="xs:string"/>
              <xs:element name="DatePublished" type="xs:string"/>
              <xs:element name="Link" type="xs:anyURI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ehenderson828/xml-jquery-final/data/eric.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="xslt/eric.xsl"?>

<!--
   CMT-117 & CMT-225

   XML & jQuery Final Project
   Author: Eric Henderson
   Date: December 8, 2025 

   Filename:           eric.xml
   Supporting Files:   eric.xsd, eric.xsl
-->

<ericsProjects
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema/eric.xsd"
>
  <ericsProject>
     <Title>Erics48</Title>
	  <Description>
      Erics48 is a web based hiking app that allows hikers working towards their NH 48 4,000 footers list to document and share their experience hiking each mountain.
     </Description>
     <TimeToComplete>2 months</TimeToComplete>
	  <DatePublished>May 2024</DatePublished>
	  <Link>
      https://erics48.vercel.app/register
     </Link>
  </ericsProject>
  <ericsProject>
     <Title>Bonsai Sensor Dashboard</Title>
	  <Description>
      My Bonsai Sensor Data project is a dashboard that renders daily temperature, humidity and atmospheric pressure for my collection of bonsai trees.
     </Description>
     <TimeToComplete>1 month</TimeToComplete>
	  <DatePublished>September 2025</DatePublished>
	  <Link>
      https://erics-bonsai-dashboard.vercel.app/
     </Link>
  </ericsProject>
  <ericsProject>
     <Title>Brosco Weather Dashboard</Title>
	  <Description>
      Up to date weather data dashboard being rendered in Brosco employee break rooms in both the Portland, Maine and Westfield, Massachusetts. 
     </Description>
     <TimeToComplete>2 weeks</TimeToComplete>
	  <DatePublished>June 2024</DatePublished>
	  <Link>
      https://vue-weather-zeta.vercel.app/
     </Link>
  </ericsProject>
</ericsProjects>
