=== ehenderson828/xml-jquery-final/data/schema/niko.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
   CMT-117 & CMT-225

   XML & jQuery Final Project
   Author: NÃ­ko Ferdinand
   Date:  

   Filename:          niko.xsd
   Supporting Files:  niko.xml
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

</xs:schema>

<xs:element name="nikosProject">
	<xs:complexType>  

	<xs:sequence>
		<xs:element name="Title" type="xs:string"/>
		<xs:element name="Description" type="xs:string"/>	
		<xs:element name="TimeToComplete" type="xs:string"/>
		<xs:element name="DatePublished" type="xs:string"/>
		<xs:element name="Link" type="xs:string"/>
			</xs:sequence>

		</xs:complexType> 
	</xs:element>

<xs:element name="nikosProjects">
 <xs:complexType>
  <xs:sequence>

		<xs:element 
		ref="nikosProject" 
		minOccurs="1"
		maxOccurs="unbounded" 
		type="xs:string" /> 
	
  </xs:sequence>
 </xs:complexType>  
</xs:element>
	
	
	
	
</xs:schema>

=== ehenderson828/xml-jquery-final/data/niko.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--?xml-stylesheet type="text/css" href="/styles/xmlstyles.css"?-->
<?xml-stylesheet type="text/xsl" href="xslt/niko.xsl"?>
<!--
   CMT-117 & CMT-225

   XML & jQuery Final Project
   Author: NÃ­ko Ferdinand
   Date:

   Filename:           niko.xml
   Supporting Files:   niko.xsd, niko.xsl
-->
<nikosProjects
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema/niko.xsd"
>

  <nikosProject>
     <Title>Persuasio</Title>
	 <Description>A website showcasing how to gain confidence and talk to people.</Description>
     <TimeToComplete>3 weeks</TimeToComplete>
	 <DatePublished>April 2024</DatePublished>
	 <Link>https://www.nissertation.com</Link>
  </nikosProject>

  <nikosProject>
     <Title>Pee</Title>
	 <Description>A. Spacebuns.</Description>
     <TimeToComplete>8 days</TimeToComplete>
	 <DatePublished>May 2025</DatePublished>
	 <Link>https://wwww.pee</Link>
  </nikosProject>
  
  <nikosProject>
     <Title>New England Birds</Title>
	 <Description>A website showcasing information about New England states, including state birds, flowers, and leadership.</Description>
     <TimeToComplete>2 weeks</TimeToComplete>
	 <DatePublished>February 2025</DatePublished>
	 <Link>https://www.newenglandbirdies.com</Link>
  </nikosProject>
  
  <nikosProject>
     <Title>Stoic Quotes</Title>
	 <Description>A look into the minds of famous Stoic and Epicurean philosophers.</Description>
     <TimeToComplete>4 days</TimeToComplete>
	 <DatePublished>January 2025</DatePublished>
	 <Link>https://www.Wstoicism.ca</Link>
  </nikosProject>


</nikosProjects>
